
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n07: tasks 20,24: Exited with exit code 1
srun: Terminating StepId=59357629.0
srun: error: sh03-04n03: tasks 10,16: Exited with exit code 1
slurmstepd: error: *** STEP 59357629.0 ON sh03-04n01 CANCELLED AT 2025-02-05T01:44:33 ***
srun: error: sh03-04n01: tasks 0-9: Terminated
srun: error: sh03-04n03: tasks 11-15,17: Terminated
srun: error: sh03-04n07: tasks 18-19,21-23: Terminated
srun: Force Terminated StepId=59357629.0
srun: Step created for StepId=59357629.1
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
srun: Terminating StepId=59357629.1
slurmstepd: error: *** STEP 59357629.1 ON sh03-04n01 CANCELLED AT 2025-02-05T01:44:34 ***
srun: error: sh03-04n03: tasks 10-17: Exited with exit code 1
srun: error: sh03-04n01: tasks 0-9: Terminated
srun: Force Terminated StepId=59357629.1
srun: Step created for StepId=59357629.2
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
srun: Terminating StepId=59357629.2
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n03: tasks 10-17: Exited with exit code 1
slurmstepd: error: *** STEP 59357629.2 ON sh03-04n01 CANCELLED AT 2025-02-05T01:44:36 ***
srun: error: sh03-04n01: tasks 0-9: Terminated
srun: Force Terminated StepId=59357629.2
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
srun: Terminating StepId=59357629.3
slurmstepd: error: *** STEP 59357629.3 ON sh03-04n01 CANCELLED AT 2025-02-05T01:44:37 ***
srun: error: sh03-04n03: tasks 10-11,13,16-17: Terminated
srun: error: sh03-04n03: tasks 12,14-15: Exited with exit code 1
srun: error: sh03-04n01: tasks 0-9: Terminated
srun: Force Terminated StepId=59357629.3
srun: Step created for StepId=59357629.4
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n03: tasks 11,14,16: Exited with exit code 1
srun: Terminating StepId=59357629.4
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
slurmstepd: error: *** STEP 59357629.4 ON sh03-04n01 CANCELLED AT 2025-02-05T01:44:39 ***
srun: error: sh03-04n03: tasks 10,13,15,17: Terminated
srun: error: sh03-04n03: task 12: Exited with exit code 1
srun: error: sh03-04n01: tasks 0-9: Terminated
srun: Force Terminated StepId=59357629.4
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
srun: Terminating StepId=59357629.5
slurmstepd: error: *** STEP 59357629.5 ON sh03-04n01 CANCELLED AT 2025-02-05T01:44:41 ***
srun: error: sh03-04n03: task 10: Exited with exit code 1
srun: error: sh03-04n03: tasks 11-17: Terminated
srun: error: sh03-04n01: tasks 0-9: Terminated
srun: Force Terminated StepId=59357629.5
srun: Step created for StepId=59357629.6
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
srun: Terminating StepId=59357629.6
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
    from . import _ccllib
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n03: tasks 10-17: Exited with exit code 1
slurmstepd: error: *** STEP 59357629.6 ON sh03-04n01 CANCELLED AT 2025-02-05T01:44:43 ***
srun: error: sh03-04n01: tasks 0-9: Terminated
srun: Force Terminated StepId=59357629.6
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
srun: Terminating StepId=59357629.7
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n03: tasks 10-17: Exited with exit code 1
slurmstepd: error: *** STEP 59357629.7 ON sh03-04n01 CANCELLED AT 2025-02-05T01:44:45 ***
srun: error: sh03-04n01: tasks 0-9: Terminated
srun: Force Terminated StepId=59357629.7
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
srun: Terminating StepId=59357629.8
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n03: tasks 10-17: Exited with exit code 1
slurmstepd: error: *** STEP 59357629.8 ON sh03-04n01 CANCELLED AT 2025-02-05T01:44:47 ***
srun: error: sh03-04n01: tasks 0-9: Terminated
srun: Force Terminated StepId=59357629.8
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n03: task 12: Exited with exit code 1
srun: Terminating StepId=59357629.9
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
slurmstepd: error: *** STEP 59357629.9 ON sh03-04n01 CANCELLED AT 2025-02-05T01:44:49 ***
srun: error: sh03-04n03: tasks 10-11,13-17: Terminated
srun: error: sh03-04n01: tasks 0-9: Terminated
srun: Force Terminated StepId=59357629.9
srun: Step created for StepId=59357629.10
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
srun: Terminating StepId=59357629.10
srun: error: sh03-04n03: tasks 10-11,14,16: Exited with exit code 1
slurmstepd: error: *** STEP 59357629.10 ON sh03-04n01 CANCELLED AT 2025-02-05T01:44:51 ***
srun: error: sh03-04n03: task 12: Exited with exit code 1
srun: error: sh03-04n03: tasks 13,15,17: Terminated
srun: error: sh03-04n01: tasks 0-9: Terminated
srun: Force Terminated StepId=59357629.10
srun: Step created for StepId=59357629.11
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
srun: Terminating StepId=59357629.11
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n01: tasks 0-1,6-9: Exited with exit code 1
slurmstepd: error: *** STEP 59357629.11 ON sh03-04n01 CANCELLED AT 2025-02-05T01:44:53 ***
srun: error: sh03-04n01: tasks 2-4: Terminated
srun: error: sh03-04n01: task 5: Exited with exit code 1
srun: error: sh03-04n03: tasks 10-17: Terminated
srun: Force Terminated StepId=59357629.11
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
srun: Terminating StepId=59357629.12
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n03: tasks 10,12,14: Exited with exit code 1
srun: error: sh03-04n01: tasks 0-9: Exited with exit code 1
srun: error: sh03-04n03: tasks 11,13,15-17: Terminated
srun: Force Terminated StepId=59357629.12
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
srun: Terminating StepId=59357629.13
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n03: tasks 10,14: Exited with exit code 1
srun: error: sh03-04n01: tasks 0-9: Exited with exit code 1
srun: error: sh03-04n03: tasks 11-13,15-17: Terminated
srun: Force Terminated StepId=59357629.13
srun: Step created for StepId=59357629.14
