
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n03: task 14: Exited with exit code 1
srun: Terminating StepId=59357676.0
slurmstepd: error: *** STEP 59357676.0 ON sh03-04n01 CANCELLED AT 2025-02-05T01:47:21 ***
srun: error: sh03-04n03: tasks 10-13,15-16: Terminated
srun: error: sh03-04n03: task 17: Exited with exit code 1
srun: error: sh03-04n07: tasks 18-24: Terminated
srun: error: sh03-04n01: tasks 0-9: Terminated
srun: Force Terminated StepId=59357676.0
srun: Step created for StepId=59357676.1
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
srun: error: sh03-04n03: tasks 10-12,14,16: Exited with exit code 1
    from . import ccllib as lib
srun: Terminating StepId=59357676.1
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n07: tasks 18,20-24: Exited with exit code 1
slurmstepd: error: *** STEP 59357676.1 ON sh03-04n01 CANCELLED AT 2025-02-05T01:47:23 ***
srun: error: sh03-04n07: task 19: Terminated
srun: error: sh03-04n03: task 13: Exited with exit code 1
srun: error: sh03-04n03: tasks 15,17: Terminated
srun: error: sh03-04n01: tasks 0-9: Terminated
srun: Force Terminated StepId=59357676.1
srun: Step created for StepId=59357676.2
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
srun: Terminating StepId=59357676.2
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n03: tasks 10-17: Exited with exit code 1
srun: error: sh03-04n01: tasks 0,2,4-9: Exited with exit code 1
slurmstepd: error: *** STEP 59357676.2 ON sh03-04n01 CANCELLED AT 2025-02-05T01:47:25 ***
srun: error: sh03-04n01: tasks 1,3: Terminated
srun: Force Terminated StepId=59357676.2
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
srun: Terminating StepId=59357676.3
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n03: tasks 10-11,13-17: Exited with exit code 1
srun: error: sh03-04n01: tasks 3-9: Exited with exit code 1
slurmstepd: error: *** STEP 59357676.3 ON sh03-04n01 CANCELLED AT 2025-02-05T01:47:27 ***
srun: error: sh03-04n03: task 12: Terminated
srun: error: sh03-04n01: tasks 0-2: Terminated
srun: Force Terminated StepId=59357676.3
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
srun: Terminating StepId=59357676.4
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n03: tasks 10-15,17: Exited with exit code 1
srun: error: sh03-04n01: tasks 0,2-9: Exited with exit code 1
slurmstepd: error: *** STEP 59357676.4 ON sh03-04n01 CANCELLED AT 2025-02-05T01:47:29 ***
srun: error: sh03-04n03: task 16: Terminated
srun: error: sh03-04n01: task 1: Exited with exit code 1
srun: Force Terminated StepId=59357676.4
srun: Step created for StepId=59357676.5
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
srun: Terminating StepId=59357676.5
slurmstepd: error: *** STEP 59357676.5 ON sh03-04n01 CANCELLED AT 2025-02-05T01:47:31 ***
srun: error: sh03-04n03: tasks 10-17: Terminated
srun: error: sh03-04n01: tasks 0-9: Terminated
srun: Force Terminated StepId=59357676.5
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
srun: Terminating StepId=59357676.6
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n03: tasks 12-17: Exited with exit code 1
srun: error: sh03-04n01: tasks 2,6: Exited with exit code 1
slurmstepd: error: *** STEP 59357676.6 ON sh03-04n01 CANCELLED AT 2025-02-05T01:47:34 ***
srun: error: sh03-04n03: tasks 10-11: Terminated
srun: error: sh03-04n01: tasks 0-1,3-5,7-9: Terminated
srun: Force Terminated StepId=59357676.6
srun: Step created for StepId=59357676.7
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n07: tasks 19-24: Exited with exit code 1
srun: Terminating StepId=59357676.7
srun: error: sh03-04n03: tasks 11-12,14,16: Exited with exit code 1
slurmstepd: error: *** STEP 59357676.7 ON sh03-04n01 CANCELLED AT 2025-02-05T01:47:36 ***
srun: error: sh03-04n07: task 18: Terminated
srun: error: sh03-04n03: task 10: Exited with exit code 1
srun: error: sh03-04n03: tasks 13,15,17: Terminated
srun: error: sh03-04n01: tasks 0-9: Terminated
srun: Force Terminated StepId=59357676.7
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
srun: Terminating StepId=59357676.8
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n03: tasks 10,12-17: Exited with exit code 1
srun: error: sh03-04n01: tasks 0-6,8-9: Exited with exit code 1
slurmstepd: error: *** STEP 59357676.8 ON sh03-04n01 CANCELLED AT 2025-02-05T01:47:38 ***
srun: error: sh03-04n03: task 11: Terminated
srun: error: sh03-04n01: task 7: Terminated
srun: Force Terminated StepId=59357676.8
srun: Step created for StepId=59357676.9
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
srun: Terminating StepId=59357676.9
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n03: tasks 10-17: Exited with exit code 1
srun: error: sh03-04n01: tasks 0-9: Exited with exit code 1
srun: Step created for StepId=59357676.10
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
srun: Terminating StepId=59357676.10
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n03: tasks 10-13,15-17: Exited with exit code 1
srun: error: sh03-04n01: tasks 0,2-9: Exited with exit code 1
slurmstepd: error: *** STEP 59357676.10 ON sh03-04n01 CANCELLED AT 2025-02-05T01:47:42 ***
srun: error: sh03-04n01: task 1: Exited with exit code 1
srun: error: sh03-04n03: task 14: Terminated
srun: Force Terminated StepId=59357676.10
srun: Step created for StepId=59357676.11
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
srun: Terminating StepId=59357676.11
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n03: tasks 10-17: Exited with exit code 1
srun: error: sh03-04n01: tasks 1-3,5-9: Exited with exit code 1
slurmstepd: error: *** STEP 59357676.11 ON sh03-04n01 CANCELLED AT 2025-02-05T01:47:44 ***
srun: error: sh03-04n01: task 0: Terminated
srun: error: sh03-04n01: task 4: Exited with exit code 1
srun: Force Terminated StepId=59357676.11
srun: Step created for StepId=59357676.12
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
srun: Terminating StepId=59357676.12
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n03: tasks 10-17: Exited with exit code 1
slurmstepd: error: *** STEP 59357676.12 ON sh03-04n01 CANCELLED AT 2025-02-05T01:47:46 ***
srun: error: sh03-04n01: tasks 1,3-4,6: Terminated
srun: error: sh03-04n01: tasks 2,5,7-9: Exited with exit code 1
srun: error: sh03-04n01: task 0: Terminated
srun: Force Terminated StepId=59357676.12
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
srun: Terminating StepId=59357676.13
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n03: tasks 13-15,17: Exited with exit code 1
srun: error: sh03-04n01: tasks 0-3,5-7: Exited with exit code 1
slurmstepd: error: *** STEP 59357676.13 ON sh03-04n01 CANCELLED AT 2025-02-05T01:47:48 ***
srun: error: sh03-04n03: tasks 10-12,16: Terminated
srun: error: sh03-04n01: tasks 4,8-9: Terminated
srun: Force Terminated StepId=59357676.13
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
srun: Terminating StepId=59357676.14
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n03: tasks 10-17: Exited with exit code 1
srun: error: sh03-04n01: tasks 0-9: Exited with exit code 1
srun: Step created for StepId=59357676.15
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
srun: Terminating StepId=59357676.15
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n01: tasks 5-6,8: Exited with exit code 1
srun: error: sh03-04n03: tasks 10-17: Exited with exit code 1
slurmstepd: error: *** STEP 59357676.15 ON sh03-04n01 CANCELLED AT 2025-02-05T01:47:52 ***
srun: error: sh03-04n01: tasks 0-4,7,9: Terminated
srun: Force Terminated StepId=59357676.15
srun: Step created for StepId=59357676.16
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n07: tasks 18-24: Exited with exit code 1
srun: Terminating StepId=59357676.16
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
Traceback (most recent call last):
  File "/oak/stanford/orgs/kipac/users/mahlet/bias/scripts/mpi_ksum.py", line 7, in <module>
    import pyccl as ccl
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/__init__.py", line 15, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import ccllib as lib
  File "/home/users/mahlet/miniconda3/lib/python3.9/site-packages/pyccl/ccllib.py", line 19, in <module>
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
    from . import _ccllib
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
srun: error: sh03-04n01: tasks 0-9: Exited with exit code 1
